### ISSUE TITLE
Null check in chat

### ISSUE THREAD

**Issue by kahl11** [kahl11/bookheroApp#11]
If the chat server goes down or doesnt return a message for some reason, the entire chats screen will die. This can be fixed with a null check on the `recent` object. https://github.com/kahl11/bookheroApp/blob/d3181986b2eb48f0e69772b2f8edb4b5e2387ab9/screens/chatLanding.tsx#L63-L68

**Comment by nmakarowski** [comment]
![image](https://user-images.githubusercontent.com/37052386/163893499-9bbaaaf5-0f3d-4137-b061-34be95c1711f.png)
